# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-31 15:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('brandid', '0002_auto_20160327_1508'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogoComapny',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('old_logo', models.BooleanField()),
                ('upload_old_logo', models.ImageField(upload_to='old_logo')),
                ('reason_logo', models.TextField()),
                ('target_audience', models.TextField()),
                ('competition', models.BooleanField()),
                ('desc_competition', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LogoProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagline', models.CharField(max_length=120)),
                ('include_tagline', models.BooleanField()),
                ('imagery', models.TextField()),
                ('my_brand_colour', models.BooleanField()),
                ('brand_colours', models.TextField()),
                ('pref_colour', models.BooleanField()),
                ('list_pref_colour', models.TextField()),
                ('logo_adjective', models.CharField(max_length=25)),
                ('logo_message', models.TextField()),
                ('typography', models.CharField(max_length=25)),
                ('logo_location', models.CharField(max_length=25)),
                ('deadline', models.DateField()),
                ('budget', models.CharField(max_length=50)),
                ('other_services', models.TextField()),
                ('inspired_logos', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Talk',
        ),
        migrations.AddField(
            model_name='contact',
            name='added',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 3, 31, 15, 29, 50, 309815, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
