# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-31 17:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brandid', '0003_auto_20160331_1629'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LogoComapny',
            new_name='LogoCompany',
        ),
    ]
