# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-31 18:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brandid', '0004_auto_20160331_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='logoproject',
            name='company',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='brandid.LogoCompany'),
            preserve_default=False,
        ),
    ]
