# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-31 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brandid', '0005_logoproject_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logocompany',
            name='upload_old_logo',
            field=models.ImageField(blank=True, upload_to='old_logo'),
        ),
    ]
