# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-01 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brandid', '0007_auto_20160331_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='logocompany',
            name='logo_id',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
